server:
  port: 9000

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# JWT 설정
jwt:
  secret: a2V5aXN2ZXJ5dmVyeXZlcnl2ZXJ5dmVyeXZlcnlzZWNyZXRrZXlmb3JtaWNyb3NlcnZpY2VzZXhhbXBsZQ==
  access-token-validity: 3600  # 1시간
  refresh-token-validity: 86400  # 24시간 